#include "acc_user.h"
#include "stdio.h"

  FILE *f_monitor;

  handle mrst;
  handle mclk;
  handle IR;
  handle AC;
  handle DR;
  handle E;
  handle I;
  handle FGI;
  handle FGO;
  handle S;
  handle R;
  handle IEN;
  handle alua;
  handle alub;
  handle aluout;
  handle inprin;
  handle TR;
  handle AR;
  handle PC;
  handle INPR;
  handle OUTR;
  handle memout;
  handle busout;
  handle cs_ar_clr;
  handle cs_ir_clr;
  handle cs_pc_clr;
  handle cs_dr_clr;
  handle cs_ac_clr;
  handle cs_tr_clr;
  handle cs_inpr_clr;
  handle cs_outr_clr;
  handle cs_ar_inc;
  handle cs_ir_inc;
  handle cs_pc_inc;
  handle cs_dr_inc;
  handle cs_ac_inc;
  handle cs_tr_inc;
  handle cs_inpr_inc;
  handle cs_outr_inc;
  handle cs_ar_ld;
  handle cs_ir_ld;
  handle cs_pc_ld;
  handle cs_dr_ld;
  handle cs_ac_ld;
  handle cs_tr_ld;
  handle cs_inpr_ld;
  handle cs_outr_ld;
  handle cs_s_ld;
  handle cs_s_clr;
  handle cs_e_ld;
  handle cs_e_clr;
  handle cs_i_ld;
  handle cs_i_clr;
  handle cs_fgi_ld;
  handle cs_fgi_clr,cs_fgo_ld;
  handle cs_fgo_clr;
  handle cs_r_ld;
  handle cs_r_clr;
  handle cs_ien_ld;
  handle cs_ien_clr;
  handle cs_mem_rd;
  handle cs_mem_wr;
  handle s_in;
  handle ien_in;
  handle fgi_in;
  handle fgo_in;
  handle r_in;
  handle cs_bus_sel;
  handle cs_alu_func;
  handle cs_alub_sel;

void monitor_mano_dp();

void mano_alu_monitor() 
{
  acc_initialize();
  mrst = acc_handle_tfarg(1);
  mclk = acc_handle_tfarg(2);
  IR = acc_handle_tfarg(3);
  AC = acc_handle_tfarg(4);
  DR = acc_handle_tfarg(5);
  E = acc_handle_tfarg(6);
  I = acc_handle_tfarg(7);
  FGI = acc_handle_tfarg(8);
  FGO = acc_handle_tfarg(9);
  S = acc_handle_tfarg(10);
  R = acc_handle_tfarg(11);
  IEN = acc_handle_tfarg(12);
  alua = acc_handle_tfarg(13);
  alub = acc_handle_tfarg(14);
  aluout = acc_handle_tfarg(15);
  inprin = acc_handle_tfarg(16);
  TR = acc_handle_tfarg(17);
  AR = acc_handle_tfarg(18);
  PC = acc_handle_tfarg(19);
  INPR = acc_handle_tfarg(20);
  OUTR = acc_handle_tfarg(21);
  memout = acc_handle_tfarg(22);
  busout = acc_handle_tfarg(23);
  cs_ar_clr = acc_handle_tfarg(24);
  cs_ir_clr = acc_handle_tfarg(25);
  cs_pc_clr = acc_handle_tfarg(26);
  cs_dr_clr = acc_handle_tfarg(27);
  cs_ac_clr = acc_handle_tfarg(28);
  cs_tr_clr = acc_handle_tfarg(29);
  cs_inpr_clr = acc_handle_tfarg(30);
  cs_outr_clr = acc_handle_tfarg(31);
  cs_ar_inc = acc_handle_tfarg(32);
  cs_ir_inc = acc_handle_tfarg(33);
  cs_pc_inc = acc_handle_tfarg(34);
  cs_dr_inc = acc_handle_tfarg(35);
  cs_ac_inc = acc_handle_tfarg(36);
  cs_tr_inc = acc_handle_tfarg(37);
  cs_inpr_inc = acc_handle_tfarg(38);
  cs_outr_inc = acc_handle_tfarg(39);
  cs_ar_ld = acc_handle_tfarg(40);
  cs_ir_ld = acc_handle_tfarg(41);
  cs_pc_ld = acc_handle_tfarg(42);
  cs_dr_ld = acc_handle_tfarg(43);
  cs_ac_ld = acc_handle_tfarg(44);
  cs_tr_ld = acc_handle_tfarg(45);
  cs_inpr_ld = acc_handle_tfarg(46);
  cs_outr_ld = acc_handle_tfarg(47);
  cs_s_ld = acc_handle_tfarg(48);
  cs_s_clr = acc_handle_tfarg(49);
  cs_e_ld = acc_handle_tfarg(50);
  cs_e_clr = acc_handle_tfarg(51);
  cs_i_ld = acc_handle_tfarg(52);
  cs_i_clr = acc_handle_tfarg(53);
  cs_fgi_ld = acc_handle_tfarg(54);
  cs_fgo_ld = acc_handle_tfarg(55);
  cs_fgo_clr = acc_handle_tfarg(56);
  cs_r_ld = acc_handle_tfarg(57);
  cs_r_clr = acc_handle_tfarg(58);
  cs_ien_ld = acc_handle_tfarg(59);
  cs_ien_clr = acc_handle_tfarg(60);
  cs_mem_rd = acc_handle_tfarg(61);
  cs_mem_wr = acc_handle_tfarg(62);
  s_in = acc_handle_tfarg(63);
  ien_in = acc_handle_tfarg(64);
  fgi_in = acc_handle_tfarg(65);
  fgo_in = acc_handle_tfarg(66);
  r_in = acc_handle_tfarg(67);  
  cs_bus_sel = acc_handle_tfarg(68);
  cs_alu_func = acc_handle_tfarg(69);
  cs_alub_sel = acc_handle_tfarg(70);
  acc_vcl_add( mclk, monitor_mano_d, null, vcl_verilog_logic);
  acc_close();
}

void monitor_mano_dp()
{
  f_monitor = fopen ("monitor.dat","a");
  fprintf(f_monitor, "ALALA");
  fprintf(f_monitor, "%s\n", acc_fetch_value(mrst, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(mclk, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(IR, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(AC, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(DR, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(E, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(I, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(FGI, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(FGO, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(S, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(R, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(IEN, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(alua, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(alub, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(aluout, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(inprin, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(TR, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(AR, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(PC, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(INPR, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(OUTR, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(memout, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(busout, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ar_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ir_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_pc_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_dr_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ac_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_tr_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_inpr_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_outr_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ar_inc, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ir_inc, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_pc_inc, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_dr_inc, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ac_inc, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_tr_inc, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_inpr_inc, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_outr_inc, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ar_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ir_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_pc_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_dr_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ac_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_tr_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_inpr_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_outr_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_s_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_s_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_e_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_e_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_i_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_i_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_fgi_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_fgo_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_fgo_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_r_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_r_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ien_ld, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_ien_clr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_mem_rd, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_mem_wr, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(s_in, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(ien_in, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(fgi_in, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(fgo_in, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(r_in, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_bus_sel, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_alu_func, "%b", null));
  fprintf(f_monitor, "%s\n", acc_fetch_value(cs_alub_sel, "%b", null));
  fprintf(f_monitor, "----------------------------\n");
  fclose (f_monitor);
}
